version: '3.4'

services:
  web:
    build: .
    ports:
    - ${LOCAL_PORT:-8080}:8080
    environment:
      AMADEUS_CLIENT_ID: ${AMADEUS_CLIENT_ID:-}
      AMADEUS_CLIENT_SECRET: ${AMADEUS_CLIENT_SECRET:-}
      HERE_API_KEY: ${HERE_API_KEY:-}
      AMADEUS_HOSTNAME: "test"
